name: Hello World CI   # name of the workflow

on: [push]   # run every time you push code

jobs:
  hello:
    runs-on: ubuntu-latest   # GitHub gives you a free Linux computer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "👋 Hello from GitHub CI!"
