name: Security Scan CI

on: [push]

jobs:
  bandit-scan:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3) Install dependencies
      - name: Install dependencies
        run: pip install -r ./requirements.txt

      # 4) Run Bandit Security Scan
      - name: Run Bandit Security Scan
        run: bandit -r ./demos/vulnerable_app || true
